# Mapping from ISO 639-1 language codes to country folder names in icon_assets
LANG_TO_COUNTRY = {
    "en": "united_states",
    "es": "spain",
    "fr": "france",
    "de": "germany",
    "it": "italy",
    "pt": "brazil",
    "ru": "russia",
    "ja": "japan",
    "ko": "south_korea",
    "zh": "china",
    "hi": "india",
    "ar": "saudi_arabia",
    "bn": "bangladesh",
    "pa": "india",
    "jv": "indonesia",
    "te": "india",
    "vi": "vietnam",
    "mr": "india",
    "ta": "india",
    "tr": "turkey",
    "ur": "pakistan",
    "pl": "poland",
    "uk": "ukraine",
    "nl": "netherlands",
    "el": "greece",
    "th": "thailand",
    "sv": "sweden",
    "da": "denmark",
    "fi": "finland",
    "no": "norway",
    "he": "israel",
    "id": "indonesia",
    "ms": "malaysia",
    "hu": "hungary",
    "cs": "czech_republic",
    "ro": "romania",
    "sk": "slovakia",
    "bg": "bulgaria",
    "hr": "croatia",
    "sr": "serbia",
    "sl": "slovenia",
    "et": "estonia",
    "lv": "latvia",
    "lt": "lithuania",
    "fa": "iran",
    "sw": "kenya",
    "tl": "philippines",
    "is": "iceland",
    "ga": "republic_of_ireland",
    "cy": "united_kingdom",
    "gd": "united_kingdom",
    "lb": "luxembourg",
    "mt": "malta",
    "sq": "albania",
    "hy": "armenia",
    "az": "azerbaijan",
    "ka": "armenia",  # Fallback for Georgia which is missing
    "kk": "kazakhstan",
    "ky": "kyrgyzstan",
    "tg": "tajikistan",
    "tk": "turkmenistan",
    "uz": "uzbekistan",
    "mn": "mongolia",
    "bo": "china",
    "my": "myanmar",
    "km": "cambodia",
    "lo": "laos",
    "ml": "india",
    "kn": "india",
    "si": "sri_lanka",
    "ne": "nepal",
    "ps": "afghanistan",
    "ku": "iraq",
    "am": "ethiopia",
    "yo": "nigeria",
    "ig": "nigeria",
    "zu": "south_africa",
    "xh": "south_africa",
    "af": "south_africa",
    "mi": "new_zealand",
    "haw": "united_states",
    "sm": "samoa",
    "to": "tonga",
    "fj": "fiji",
    "eo": "esperanto",
    "ca": "spain",
    "gl": "spain",
    "eu": "spain",
    "oc": "france",
    "br": "france",
    "co": "france",
    "fy": "netherlands",
    "hsb": "germany",
    "csb": "poland",
    "tt": "russia",
    "ba": "russia",
    "ce": "russia",
    "cv": "russia",
    "udm": "russia",
    "mhr": "russia",
    "sah": "russia",
    "gn": "paraguay",
    "qu": "peru",
    "ay": "bolivia",
    "nah": "mexico",
    "yua": "mexico",
}

# Regional mapping for ordering
COUNTRY_TO_REGION = {
    "spain": "Europe",
    "france": "Europe",
    "germany": "Europe",
    "italy": "Europe",
    "poland": "Europe",
    "ukraine": "Europe",
    "netherlands": "Europe",
    "greece": "Europe",
    "sweden": "Europe",
    "denmark": "Europe",
    "finland": "Europe",
    "norway": "Europe",
    "hungary": "Europe",
    "czech_republic": "Europe",
    "romania": "Europe",
    "slovakia": "Europe",
    "bulgaria": "Europe",
    "croatia": "Europe",
    "serbia": "Europe",
    "slovenia": "Europe",
    "estonia": "Europe",
    "latvia": "Europe",
    "lithuania": "Europe",
    "iceland": "Europe",
    "republic_of_ireland": "Europe",
    "united_kingdom": "Europe",
    "luxembourg": "Europe",
    "malta": "Europe",
    "albania": "Europe",
    "armenia": "Europe",
    "azerbaijan": "Europe",
    "georgia": "Europe",
    "russia": "Europe",
    "japan": "Asia",
    "south_korea": "Asia",
    "china": "Asia",
    "india": "Asia",
    "saudi_arabia": "Asia",
    "bangladesh": "Asia",
    "indonesia": "Asia",
    "vietnam": "Asia",
    "turkey": "Asia",
    "pakistan": "Asia",
    "thailand": "Asia",
    "israel": "Asia",
    "malaysia": "Asia",
    "iran": "Asia",
    "philippines": "Asia",
    "kazakhstan": "Asia",
    "kyrgyzstan": "Asia",
    "tajikistan": "Asia",
    "turkmenistan": "Asia",
    "uzbekistan": "Asia",
    "mongolia": "Asia",
    "myanmar": "Asia",
    "cambodia": "Asia",
    "laos": "Asia",
    "sri_lanka": "Asia",
    "nepal": "Asia",
    "afghanistan": "Asia",
    "iraq": "Asia",
    "kenya": "Africa",
    "ethiopia": "Africa",
    "nigeria": "Africa",
    "south_africa": "Africa",
    "united_states": "North America",
    "mexico": "North America",
    "brazil": "South America",
    "paraguay": "South America",
    "peru": "South America",
    "bolivia": "South America",
    "new_zealand": "Oceania",
    "samoa": "Oceania",
    "tonga": "Oceania",
    "fiji": "Oceania",
    "esperanto": "Global",
    "global": "Global",
}

REGION_ORDER = [
    "Europe",
    "Asia",
    "Africa",
    "North America",
    "South America",
    "Oceania",
    "Global",
]

# Specifically requested priority languages for the start of the list
PRIORITY_LANGS = ["en", "es", "gl", "it", "pt", "fr", "de"]

# Mapping of language codes to specific Noto fonts
FONT_MAP = {
    "zh": "fonts/NotoSansSC-Regular.otf",
    "ja": "fonts/NotoSansJP-Regular.otf",
    "ko": "fonts/NotoSansKR-Regular.otf",
    "my": "fonts/NotoSansMyanmar-Regular.ttf",
    "hi": "fonts/NotoSansDevanagari-Regular.ttf",
    "mr": "fonts/NotoSansDevanagari-Regular.ttf",
    "ne": "fonts/NotoSansDevanagari-Regular.ttf",
    "ar": "fonts/NotoSansArabic-Regular.ttf",
    "ur": "fonts/NotoSansArabic-Regular.ttf",
    "fa": "fonts/NotoSansArabic-Regular.ttf",
    "ps": "fonts/NotoSansArabic-Regular.ttf",
    "bn": "fonts/NotoSansBengali-Regular.ttf",
    "th": "fonts/NotoSansThai-Regular.ttf",
    "he": "fonts/NotoSansHebrew-Regular.ttf",
    "ta": "fonts/NotoSansTamil-Regular.ttf",
    "te": "fonts/NotoSansTelugu-Regular.ttf",
    "pa": "fonts/NotoSansGurmukhi-Regular.ttf",
    "kn": "fonts/NotoSansKannada-Regular.ttf",
    "ml": "fonts/NotoSansMalayalam-Regular.ttf",
    "si": "fonts/NotoSansSinhala-Regular.ttf",
    "km": "fonts/NotoSansKhmer-Regular.ttf",
    "lo": "fonts/NotoSansLao-Regular.ttf",
    "am": "fonts/NotoSansEthiopic-Regular.ttf",
    "hy": "fonts/NotoSansArmenian-Regular.ttf",
    "ka": "fonts/NotoSansGeorgian-Regular.ttf",
    "bo": "fonts/NotoSerifTibetan-Regular.ttf",
    "gu": "fonts/NotoSansGujarati-Regular.ttf",
}

EPONYMS = {
    "united_states": "american",
    "spain": "spanish",
    "france": "french",
    "germany": "german",
    "italy": "italian",
    "brazil": "brazilian",
    "russia": "russian",
    "japan": "japanese",
    "south_korea": "korean",
    "china": "chinese",
    "india": "indian",
    "saudi_arabia": "saudi",
    "bangladesh": "bangladeshi",
    "indonesia": "indonesian",
    "vietnam": "vietnamese",
    "turkey": "turkish",
    "pakistan": "pakistani",
    "poland": "polish",
    "ukraine": "ukrainian",
    "netherlands": "dutch",
    "greece": "greek",
    "thailand": "thai",
    "sweden": "swedish",
    "denmark": "danish",
    "finland": "finnish",
    "norway": "norwegian",
    "israel": "israeli",
    "malaysia": "malaysian",
    "hungary": "hungarian",
    "czech_republic": "czech",
    "romania": "romanian",
    "slovakia": "slovak",
    "bulgaria": "bulgarian",
    "croatia": "croatian",
    "serbia": "serbian",
    "slovenia": "slovenian",
    "estonia": "estonian",
    "latvia": "latvian",
    "lithuania": "lithuanian",
    "iran": "iranian",
    "kenya": "kenyan",
    "philippines": "filipino",
    "iceland": "icelandic",
    "ireland": "irish",
    "republic_of_ireland": "irish",
    "united_kingdom": "british",
    "luxembourg": "luxembourgish",
    "malta": "maltese",
    "albania": "albanian",
    "armenia": "armenian",
    "azerbaijan": "azerbaijani",
    "georgia": "georgian",
    "kazakhstan": "kazakh",
    "kyrgyzstan": "kyrgyz",
    "tajikistan": "tajik",
    "turkmenistan": "turkmen",
    "uzbekistan": "uzbek",
    "mongolia": "mongolian",
    "myanmar": "burmese",
    "cambodia": "cambodian",
    "laos": "laotian",
    "sri_lanka": "sri lankan",
    "nepal": "nepalese",
    "afghanistan": "afghan",
    "iraq": "iraqi",
    "ethiopia": "ethiopian",
    "nigeria": "nigerian",
    "south_africa": "south african",
    "new_zealand": "new zealander",
    "samoa": "samoan",
    "tonga": "tongan",
    "fiji": "fijian",
    "paraguay": "paraguayan",
    "peru": "peruvian",
    "bolivia": "bolivian",
    "mexico": "mexican",
}
